name: Build Bundle Executables

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - type: linux-x64
          - type: mac-x64
          - type: windows-x64

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout Sources
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Executable
        run: npm run build-exe-${{ matrix.type }}

      - name: npm pack
        run: npm pack

      - name: Attach artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: github-security-report-bundle-${{ matrix.type }}
          path: github-security-report-bundle.zip

